make run :
	cd ~/Desktop/SelfLearning/FastAPI/ && uvicorn storeapi.main:app --reload
make test:
	cd ~/Desktop/SelfLearning/FastAPI/storeapi/ && pytest
make lib:
	cd ~/Desktop/SelfLearning/FastAPI/ && pip install -r requirements.txt
make docker:
	cd ~/Desktop/SelfLearning/FastAPI && docker-compose up -d

PHONY: run test lib
